### ISSUE TITLE
url not working for a custom controller

### ISSUE THREAD

**Issue by snowwhite686** [thecodingmachine/getting-things-done-basic-edition#4]
Hi,

I created a new controller using create a controller link from MVC. And i can see the instance and files are automatically created.

But i cannot access via url.

http://localhost/gmvc/getting-things-done-basic-edition/vendor/mouf/mouf/register

All the cache purge is done.
Can you help?

Thanks
Neetha

**Comment by moufmouf** [comment]
I guess the URL should be http://localhost/gmvc/getting-things-done-basic-edition/register ?

The /vendor/mouf/mouf path is for Mouf UI only. When you write a controller, if you put @URL("/register"), then the path to your controller is http://localhost/gmvc/getting-things-done-basic-edition/register

Does it solve your problem?

**Comment by snowwhite686** [comment]
yes, i tried the url, but i can see only errors. like 
![capture_error](https://cloud.githubusercontent.com/assets/3541070/20920316/79b2c572-bbc5-11e6-8336-ddde706e1a3a.JPG)

**Comment by moufmouf** [comment]
Hey @snowwhite686 

Ok, I understand what is going on. So this is the correct URL:  http://localhost/gmvc/getting-things-done-basic-edition/register

You have a bug in there. This is not your fault, this is the fault of the documentation that is outdated. I'm in the process of updating it, it should be corrected in the afternoon. In the meanwhile, here is what your controller should look like (see below).

Let me know if this helps.



Create the controller class
---------------------------

Below is a sample class you can use as a model.
It includes what you will most likely need:

- a template
- a logger
- an access to the TDBM factory (to access database)

The code below goes into the _src/Test/Controllers/MyController.php_ file.
It is important to respect that naming convention, as it is used by the class autoloader.
If it seems strange to you, have a look at the [PSR-0](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md), 
and at the [Composer autoload documentation](http://getcomposer.org/doc/04-schema.md#autoload).

```php
<?php  
namespace Test\Controllers;

use Mouf\Mvc\Splash\Annotations\URL;
use Mouf\Html\Template\TemplateInterface;
use Mouf\Html\HtmlElement\HtmlBlock;
use Psr\Log\LoggerInterface;
use \Twig_Environment;
use Mouf\Html\Renderer\Twig\TwigTemplate;
use Mouf\Mvc\Splash\HtmlResponse;
use Zend\Diactoros\Response\JsonResponse;

class MyController {

    /**
     * The logger used by this controller.
     * @var LoggerInterface
     */
    private $logger;

    /**
     * The template used by this controller.
     * @var TemplateInterface
     */
    private $template;

    /**
     * The main content block of the page.
     * @var HtmlBlock
     */
    private $content;

    /**
     * The Twig environment (used to render Twig templates).
     * @var Twig_Environment
     */
    private $twig;

    /**
     * This method will be called when we access the /helloworld URL.*
     * It accepts an optional "echo" parameter.
     * 
     * @URL("/helloworld")
     */
    public function helloworld($echo = '') {
        // Typical code to access database goes here.
        
        // We declare the view, and bind it to the "content" block.
        // The view is declared in a Twig file.
        // Let's add the twig file to the template.
        $this->content->addHtmlElement(new TwigTemplate($this->twig, 'views/myview.twig', ["echo"=>$echo]));

        // Finally, we draw the template.
        return new HtmlResponse($this->template);
    }

    /**
     * Just echoing some text will output the text directly.
     * This is useful for Ajax calls.
     * 
     * @URL("/helloworld_ajax")
     */
    public function helloworld2() {
        return new JsonResponse(array('hello'=>'world'));
    }
}
```

<div class="alert"><strong>Heads up!</strong> Your code might be slightly different. In particular, you probably
don't use the "Test" namespace. Therefore, the <strong>use</strong> statements at the beginning of the file
might be different.</div>

Note: there is absolutely no need to put your class in a "Controllers" namespace. You can put your class in whatever
namespace you want, as long as Composer is aware of the top level namespace (aka the vendor-name).

Create a view
-------------

In this sample, we are loading a view named `myview.twig`. Let's write this file:

```twig
<h1>Hello world!</h1>
<p>echo: {{ echo }}</p>
```

This Twig file will be rendered in the view. If you are not used to Twig, you should check [Twig documentation](http://twig.sensiolabs.org/).
Twig is a great templating engine for PHP. We recommend using it by default (you can of course use any templating engine you like).

**Comment by snowwhite686** [comment]
i used the controller code, but it says an error that it doesn't have a constructor, so i added a construct function like

   /**
     * Controller's constructor.
     * @param LoggerInterface $logger The logger
     * @param TemplateInterface $template The template used by this controller
     * @param HtmlBlock $content The main content block of the page
     **_# * @param DaoFactory $daoFactory The object in charge of retrieving DAOs_**
     */
    public function __construct(LoggerInterface $logger, TemplateInterface $template, HtmlBlock $content, # **_DaoFactory $twig)_** {
        $this->logger = $logger;
        $this->template = $template;
        $this->content = $content;
        **_# $this->twig = $twig;_** 
    }


I believe the fourth parameter should be a twig object, but what would be the class then?

please advise with correction ,not sure if am right.
Thanks
Neetha

**Comment by moufmouf** [comment]
Ooops, you are right! Completely forgot the constructor. Sorry about that.

Here is the correct code (hopefully)!


```php
<?php  
namespace Test\Controllers;

use Mouf\Mvc\Splash\Annotations\URL;
use Mouf\Html\Template\TemplateInterface;
use Mouf\Html\HtmlElement\HtmlBlock;
use Psr\Log\LoggerInterface;
use \Twig_Environment;
use Mouf\Html\Renderer\Twig\TwigTemplate;
use Mouf\Mvc\Splash\HtmlResponse;
use Zend\Diactoros\Response\JsonResponse;

class MyController {

    /**
     * The logger used by this controller.
     * @var LoggerInterface
     */
    private $logger;

    /**
     * The template used by this controller.
     * @var TemplateInterface
     */
    private $template;

    /**
     * The main content block of the page.
     * @var HtmlBlock
     */
    private $content;

    /**
     * The Twig environment (used to render Twig templates).
     * @var Twig_Environment
     */
    private $twig;

    /**
     * Controller's constructor.
     * @param LoggerInterface $logger The logger
     * @param TemplateInterface $template The template used by this controller
     * @param HtmlBlock $content The main content block of the page
     * @param Twig_Environment $twig The Twig environment (used to render Twig templates)
     */
    public function __construct(LoggerInterface $logger, TemplateInterface $template, HtmlBlock $content, Twig_Environment $twig) {
        $this->logger = $logger;
        $this->template = $template;
        $this->content = $content;
        $this->twig = $twig;
    }
    
    /**
     * This method will be called when we access the /helloworld URL.*
     * It accepts an optional "echo" parameter.
     * 
     * @URL("/helloworld")
     */
    public function helloworld($echo = '') {
        // Typical code to access database goes here.
        
        // We declare the view, and bind it to the "content" block.
        // The view is declared in a Twig file.
        // Let's add the twig file to the template.
        $this->content->addHtmlElement(new TwigTemplate($this->twig, 'views/myview.twig', ["echo"=>$echo]));

        // Finally, we draw the template.
        return new HtmlResponse($this->template);
    }

    /**
     * Just echoing some text will output the text directly.
     * This is useful for Ajax calls.
     * 
     * @URL("/helloworld_ajax")
     */
    public function helloworld2() {
        return new JsonResponse(array('hello'=>'world'));
    }
}
```

When done, you should connect to the Mouf UI, go to your controller instance page and bind the "Twig" service accordingly (by drag'n'dropping the existing instance into the "twig" property of the controller.

Let me know if this works.

**Comment by snowwhite686** [comment]
yes, i dragged the twig environment instance and cache cleared, its working now.
Thank you.

**Comment by moufmouf** [comment]
:+1:

Thanks for your feedback!
